language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1
  - 2.2
  - 2.3.0
  - ruby-head
  - jruby-1.7
  - jruby-9.0.5.0
  - jruby-head

gemfile:
  - gemfiles/ruby/rails4_1.gemfile
  - gemfiles/ruby/rails4_2.gemfile
  - gemfiles/jruby/rails4_1.gemfile
  - gemfiles/jruby/rails4_2.gemfile
before_script:
  - bundle exec rake advanced_connection:db:reset
script: bundle exec rake spec
matrix:
  exclude:
    - rvm: 1.9.3
      gemfile: gemfiles/jruby/rails4_1.gemfile
    - rvm: 1.9.3
      gemfile: gemfiles/jruby/rails4_2.gemfile
    - rvm: 2.0.0
      gemfile: gemfiles/jruby/rails4_1.gemfile
    - rvm: 2.0.0
      gemfile: gemfiles/jruby/rails4_2.gemfile
    - rvm: 2.1
      gemfile: gemfiles/jruby/rails4_1.gemfile
    - rvm: 2.1
      gemfile: gemfiles/jruby/rails4_2.gemfile
    - rvm: 2.2
      gemfile: gemfiles/jruby/rails4_1.gemfile
    - rvm: 2.2
      gemfile: gemfiles/jruby/rails4_2.gemfile
    - rvm: 2.3
      gemfile: gemfiles/jruby/rails4_1.gemfile
    - rvm: 2.3
      gemfile: gemfiles/jruby/rails4_2.gemfile
    - rvm: ruby-head
      gemfile: gemfiles/jruby/rails4_1.gemfile
    - rvm: ruby-head
      gemfile: gemfiles/jruby/rails4_2.gemfile
    - rvm: jruby-1.7
      gemfile: gemfiles/ruby/rails4_1.gemfile
    - rvm: jruby-1.7
      gemfile: gemfiles/ruby/rails4_2.gemfile
    - rvm: jruby-9.0.5.0
      gemfile: gemfiles/ruby/rails4_1.gemfile
    - rvm: jruby-9.0.5.0
      gemfile: gemfiles/ruby/rails4_2.gemfile
    - rvm: jruby-head
      gemfile: gemfiles/ruby/rails4_1.gemfile
    - rvm: jruby-head
      gemfile: gemfiles/ruby/rails4_2.gemfile
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
sudo: false
cache: bundler
