---
development: &1
  pool: 50
  timeout: 5000
  queue_type: :prefer_older
  min_idle_connections: 5
  max_idle_connections: 10
  warmup_connections: 20
  dead_connection_timeout: 15
  reaping_frequency: 15
  adapter: postgresql
  database: advanced_connection_test
  username: postgres
  min_messages: WARNING
  schema_search_path: public
  password:
test: *1
