---
development: &1
  pool: 20
  timeout: 5000
  pool_queue_type: fifo
  max_idle_time: 5
  min_idle_connections: 5
  max_idle_connections: 10
  prestart_connections: 10
  dead_connection_timeout: 30
  adapter: postgresql
  database: advanced_connection_test
  username: postgres
  min_messages: WARNING
  schema_search_path: public
  password: 
test: *1
